### ISSUE TITLE
Can't rebar get-deps 

### ISSUE THREAD

**Issue by poi119** [synrc/skyline#39]
i tried to compile by used 'make & make console' but on my screen show error message
rebar get-deps
./orderapps.erl web erlydtl > .applist
ERROR: Invalid dependency specification {"../apps/web/priv/static/bootstrap",
                                         ".*",
                                         {git,
                                          "git://github.com/twbs/bootstrap",
                                          {tag,"v2.3.2"}},
                                         [raw]} in /home/ubuntu/www/skyline
make: *** [get-deps] Error 1
make: *** [.applist] Error 127
[1]+  Exit 2                  make
 
- What going wrong , my os is ubuntu 14.04 run at aws cloud

**Comment by 5HT** [comment]
Can't reproduce. For me everything OK. Maybe your problem in slow connection or something. A see that in my case the `make console` looks like that

```
$ make console
./orderapps.erl web active avz cowboy cowlib erlydtl fs gproc kvs mad n2o ranch sh > .applist
```

In your case you posted

```
./orderapps.erl web erlydtl > .applist
```

So the problem is in missed deps during fetch.

**Comment by poi119** [comment]
sorry my bad, I figure out by upgrade rebar v2.0 to v2.1 ,thanking for reply!  ,

**Comment by 5HT** [comment]
No problem, enjoy n2o!
